import { Translations } from './types';

export const TRANSLATIONS: Record<'en' | 'ur', Translations> = {
  en: {
    navTitle: "Smart AI Agriculture",
    navHome: "Home",
    navScan: "Scan Field",
    navHealth: "Crop Health",
    navLearn: "Advice",
    navWeather: "Weather",
    navMarket: "Market",
    navLanguage: "Language",
    homeTitle: "Your Partner in Modern Farming",
    homeP1: "An Entrepreneurship Project by:",
    homeP2: "This app provides localized, AI-powered agricultural assistance to Pakistani farmers. Get instant pest and disease diagnoses, weather alerts, and market price updates – all delivered in simple, clear Urdu!",
    scanTitle: "Scan Your Field & Get Instant Diagnosis",
    scanP1: "Use your device's camera to analyze your crops for diseases, pests, or nutrient deficiencies. Our AI provides immediate, actionable advice to protect your yield.",
    scanButton: "Scan Field Now",
    aiStatusReady: "Ready for scan.",
    aiStatusAnalyzing: "AI is analyzing the image... Please wait.",
    aiStatusComplete: "Analysis Complete.",
    healthTitle: "Crop Health Analytics & Alerts",
    healthP1: "Manage your crop data. Add new crops to update the analytics graph in real-time.",
    healthAddTitle: "Add New Crop",
    healthFormName: "Crop Name",
    healthFormGrowth: "Growth %",
    healthFormStatus: "Status / Notes",
    healthFormBtn: "Add Crop",
    healthListTitle: "My Crops List",
    healthNoData: "Your crop list is empty. Add a crop above to generate the health graph.",
    learnTitle: "Localized Advice & Learning",
    learnP1: "Detailed, regional guidance on crop care, pest management, and best farming practices.",
    learnCard1Title: "Wheat Care",
    learnCard1P: "Provide adequate water and nitrogen-based fertilizer. Monitor for aphids and fungal infections.",
    learnCard2Title: "Rice Care",
    learnCard2P: "Ensure proper water management. Use fungicide for fungal infection prevention. Maintain good air circulation.",
    learnCard3Title: "Corn Care",
    learnCard3P: "Monitor for aphid infestation. Use organic pest control methods and maintain soil fertility.",
    weatherTitle: "Real-time Localized Weather",
    weatherBtn: "Get Weather for My Location",
    weatherLoading: "Analyzing real-time weather patterns...",
    weatherError: "Could not fetch weather. Please allow location access.",
    weatherSources: "Sources",
    marketTitle: "Real-time Market Prices",
    marketBtn: "Get Latest Market Rates",
    marketLoading: "Searching current market prices in Pakistan...",
    marketSources: "Price Sources",
    languageModalTitle: "Choose Your Language",
    languageModalDesc: "Please select your preferred language to continue.",
    btnEnglish: "English",
    btnUrdu: "اردو (Urdu)",
  },
  ur: {
    navTitle: "سمارٹ اے آئی ایگری ایپ",
    navHome: "ہوم",
    navScan: "فیلڈ سکین",
    navHealth: "فصل کی صحت",
    navLearn: "مشورہ",
    navWeather: "موسم",
    navMarket: "قیمتیں",
    navLanguage: "زبان",
    homeTitle: "جدید کاشتکاری میں آپ کا ساتھی",
    homeP1: "انٹرپرینیورشپ پراجیکٹ از:",
    homeP2: "یہ ایپ پاکستانی کسانوں کو مقامی، AI پر مبنی زرعی مدد فراہم کرتی ہے۔ فوری کیڑوں اور بیماریوں کی تشخیص، موسم کے الرٹس، اور مارکیٹ کی قیمتوں کی اپڈیٹس حاصل کریں – یہ سب آسان اور واضح اردو میں فراہم کیا جاتا ہے!",
    scanTitle: "اپنا کھیت سکین کریں اور فوری تشخیص حاصل کریں",
    scanP1: "بیماریوں، کیڑوں یا غذائی اجزاء کی کمی کے لیے اپنی فصلوں کا تجزیہ کرنے کے لیے اپنے آلے کا کیمرہ استعمال کریں۔ ہمارا AI آپ کی پیداوار کو بچانے کے لیے فوری، قابل عمل مشورہ فراہم کرتا ہے۔",
    scanButton: "ابھی فیلڈ سکین کریں",
    aiStatusReady: "سکین کے لیے تیار۔",
    aiStatusAnalyzing: "AI تصویر کا تجزیہ کر رہا ہے... براہ کرم انتظار کریں۔",
    aiStatusComplete: "تجزیہ مکمل۔",
    healthTitle: "فصل کی صحت کا تجزیہ اور الرٹس",
    healthP1: "اپنے فصل کے ڈیٹا کا نظم کریں۔ تجزیاتی گراف کو اپ ڈیٹ کرنے کے لیے نئی فصلیں شامل کریں۔",
    healthAddTitle: "نئی فصل شامل کریں",
    healthFormName: "فصل کا نام",
    healthFormGrowth: "نشوونما %",
    healthFormStatus: "حیثیت / نوٹس",
    healthFormBtn: "فصل شامل کریں",
    healthListTitle: "میری فصلیں",
    healthNoData: "آپ کی فصل کی فہرست خالی ہے۔ ہیلتھ گراف بنانے کے لیے اوپر ایک فصل شامل کریں۔",
    learnTitle: "مقامی مشورہ اور سیکھنا",
    learnP1: "فصل کی دیکھ بھال، کیڑوں کے انتظام، اور بہترین کاشتکاری کے طریقوں پر تفصیلی، علاقائی رہنمائی۔",
    learnCard1Title: "گندم کی دیکھ بھال",
    learnCard1P: "مناسب پانی اور نائٹروجن پر مبنی کھاد فراہم کریں۔ ایفڈز اور پھپھوندی کے انفیکشن کے لیے نگرانی کریں۔",
    learnCard2Title: "چاول کی دیکھ بھال",
    learnCard2P: "پانی کا مناسب انتظام یقینی بنائیں۔ پھپھوندی کے انفیکشن سے بچاؤ کے لیے فنگسائڈ استعمال کریں۔ ہوا کی مناسب گردش کو برقرار رکھیں۔",
    learnCard3Title: "مکئی کی دیکھ بھال",
    learnCard3P: "ایفڈ کے حملے کی نگرانی کریں۔ نامیاتی کیڑوں پر قابو پانے کے طریقے استعمال کریں اور مٹی کی زرخیزی برقرار رکھیں۔",
    weatherTitle: "حقیقی وقت کا مقامی موسم",
    weatherBtn: "میری لوکیشن کا موسم حاصل کریں",
    weatherLoading: "موسم کا تجزیہ کیا جا رہا ہے...",
    weatherError: "موسم حاصل نہیں کیا جا سکا۔ براہ کرم لوکیشن تک رسائی کی اجازت دیں۔",
    weatherSources: "ذرائع",
    marketTitle: "حقیقی وقت کی مارکیٹ کی قیمتیں",
    marketBtn: "تازہ ترین مارکیٹ ریٹ حاصل کریں",
    marketLoading: "پاکستان میں مارکیٹ کی موجودہ قیمتیں تلاش کی جا رہی ہیں...",
    marketSources: "قیمت کے ذرائع",
    languageModalTitle: "اپنی زبان منتخب کریں",
    languageModalDesc: "برائے مہربانی جاری رکھنے کے لیے اپنی پسندیدہ زبان منتخب کریں۔",
    btnEnglish: "English",
    btnUrdu: "اردو (Urdu)",
  },
};