import { Translations } from './types';

export const TRANSLATIONS: Record<'en' | 'ur', Translations> = {
  en: {
    navTitle: "Smart AI Agriculture",
    navHome: "Home",
    navScan: "Scan Field",
    navHealth: "Crop Health",
    navLearn: "Advice",
    navWeather: "Weather",
    navMarket: "Market",
    homeTitle: "Your Partner in Modern Farming",
    homeP1: "An Entrepreneurship Project by: Syed Haider, Talha Anwar, Ahmad Habib",
    homeP2: "This app provides localized, AI-powered agricultural assistance to Pakistani farmers. Get instant pest and disease diagnoses, weather alerts, and market price updates – all delivered in simple, clear Urdu!",
    scanTitle: "Scan Your Field & Get Instant Diagnosis",
    scanP1: "Use your device's camera to analyze your crops for diseases, pests, or nutrient deficiencies. Our AI provides immediate, actionable advice to protect your yield.",
    scanButton: "Scan Field Now",
    aiStatusReady: "Ready for scan.",
    aiStatusAnalyzing: "AI is analyzing the image... Please wait.",
    aiStatusComplete: "Analysis Complete.",
    healthTitle: "Crop Health Analytics & Alerts",
    healthP1: "Monitor your crops' progress and receive early alerts before problems escalate.",
    healthCard1Title: "Wheat - Current Status",
    healthCard1P: "Growth: 75% | Water Level: Medium | Alert: Mild Nitrogen Deficiency Detected.",
    healthCard2Title: "Rice - Current Status",
    healthCard2P: "Growth: 60% | Water Level: High | Alert: Fungal Infection Risk High.",
    learnTitle: "Localized Advice & Learning",
    learnP1: "Detailed, regional guidance on crop care, pest management, and best farming practices.",
    learnCard1Title: "Wheat Care",
    learnCard1P: "Provide adequate water and nitrogen-based fertilizer. Monitor for aphids and fungal infections.",
    learnCard2Title: "Rice Care",
    learnCard2P: "Ensure proper water management. Use fungicide for fungal infection prevention. Maintain good air circulation.",
    learnCard3Title: "Corn Care",
    learnCard3P: "Monitor for aphid infestation. Use organic pest control methods and maintain soil fertility.",
    weatherTitle: "Localized Weather & Irrigation",
    weatherCard1Title: "Forecast",
    weatherCard1P1: "Tomorrow: Moderate rain expected in Punjab. Irrigation not required for 48 hours.",
    weatherCard1P2: "Next 3 Days: High humidity may increase fungal risk. Consider preventive measures.",
    marketTitle: "Live Market Prices (PKR)",
    marketP1: "Check the latest market rates to ensure you get the best price for your hard work.",
    marketTH1: "Crop",
    marketTH2: "Price (PKR/kg)",
    languageModalTitle: "Choose Your Language",
    languageModalDesc: "Please select your preferred language to continue.",
    btnEnglish: "English",
    btnUrdu: "اردو (Urdu)",
  },
  ur: {
    navTitle: "سمارٹ اے آئی ایگری ایپ",
    navHome: "ہوم",
    navScan: "فیلڈ سکین",
    navHealth: "فصل کی صحت",
    navLearn: "مشورہ",
    navWeather: "موسم",
    navMarket: "قیمتیں",
    homeTitle: "جدید کاشتکاری میں آپ کا ساتھی",
    homeP1: "انٹرپرینیورشپ پراجیکٹ از: سید حیدر، طلحہ انور، احمد حبیب",
    homeP2: "یہ ایپ پاکستانی کسانوں کو مقامی، AI پر مبنی زرعی مدد فراہم کرتی ہے۔ فوری کیڑوں اور بیماریوں کی تشخیص، موسم کے الرٹس، اور مارکیٹ کی قیمتوں کی اپڈیٹس حاصل کریں – یہ سب آسان اور واضح اردو میں فراہم کیا جاتا ہے!",
    scanTitle: "اپنا کھیت سکین کریں اور فوری تشخیص حاصل کریں",
    scanP1: "بیماریوں، کیڑوں یا غذائی اجزاء کی کمی کے لیے اپنی فصلوں کا تجزیہ کرنے کے لیے اپنے آلے کا کیمرہ استعمال کریں۔ ہمارا AI آپ کی پیداوار کو بچانے کے لیے فوری، قابل عمل مشورہ فراہم کرتا ہے۔",
    scanButton: "ابھی فیلڈ سکین کریں",
    aiStatusReady: "سکین کے لیے تیار۔",
    aiStatusAnalyzing: "AI تصویر کا تجزیہ کر رہا ہے... براہ کرم انتظار کریں۔",
    aiStatusComplete: "تجزیہ مکمل۔",
    healthTitle: "فصل کی صحت کا تجزیہ اور الرٹس",
    healthP1: "اپنی فصلوں کی پیشرفت کی نگرانی کریں اور مسائل کے بڑھنے سے پہلے ابتدائی الرٹس حاصل کریں۔",
    healthCard1Title: "گندم - موجودہ صورتحال",
    healthCard1P: "بڑھوتری: 75% | پانی کی سطح: درمیانی | الرٹ: ہلکی نائٹروجن کی کمی پائی گئی۔",
    healthCard2Title: "چاول - موجودہ صورتحال",
    healthCard2P: "بڑھوتری: 60% | پانی کی سطح: زیادہ | الرٹ: پھپھوندی کے انفیکشن کا خطرہ زیادہ ہے۔",
    learnTitle: "مقامی مشورہ اور سیکھنا",
    learnP1: "فصل کی دیکھ بھال، کیڑوں کے انتظام، اور بہترین کاشتکاری کے طریقوں پر تفصیلی، علاقائی رہنمائی۔",
    learnCard1Title: "گندم کی دیکھ بھال",
    learnCard1P: "مناسب پانی اور نائٹروجن پر مبنی کھاد فراہم کریں۔ ایفڈز اور پھپھوندی کے انفیکشن کے لیے نگرانی کریں۔",
    learnCard2Title: "چاول کی دیکھ بھال",
    learnCard2P: "پانی کا مناسب انتظام یقینی بنائیں۔ پھپھوندی کے انفیکشن سے بچاؤ کے لیے فنگسائڈ استعمال کریں۔ ہوا کی مناسب گردش کو برقرار رکھیں۔",
    learnCard3Title: "مکئی کی دیکھ بھال",
    learnCard3P: "ایفڈ کے حملے کی نگرانی کریں۔ نامیاتی کیڑوں پر قابو پانے کے طریقے استعمال کریں اور مٹی کی زرخیزی برقرار رکھیں۔",
    weatherTitle: "مقامی موسم اور آبپاشی کا شیڈول",
    weatherCard1Title: "پیش گوئی",
    weatherCard1P1: "کل: پنجاب میں درمیانی بارش کی توقع ہے۔ 48 گھنٹے تک آبپاشی کی ضرورت نہیں۔",
    weatherCard1P2: "اگلے 3 دن: زیادہ نمی سے پھپھوندی کا خطرہ بڑھ سکتا ہے۔ احتیاطی تدابیر پر غور کریں۔",
    marketTitle: "لائیو مارکیٹ ریٹ (PKR)",
    marketP1: "اپنی محنت کی بہترین قیمت یقینی بنانے کے لیے تازہ ترین مارکیٹ ریٹ چیک کریں۔",
    marketTH1: "فصل",
    marketTH2: "قیمت (PKR/کلوگرام)",
    languageModalTitle: "اپنی زبان منتخب کریں",
    languageModalDesc: "برائے مہربانی جاری رکھنے کے لیے اپنی پسندیدہ زبان منتخب کریں۔",
    btnEnglish: "English",
    btnUrdu: "اردو (Urdu)",
  },
};

export const MARKET_DATA = [
  { name: 'Wheat', price: 220 },
  { name: 'Rice', price: 150 },
  { name: 'Corn', price: 180 },
  { name: 'Potatoes', price: 80 },
];

export const HEALTH_DATA = [
  { name: 'Wheat', growth: 75, fill: '#546E38' },
  { name: 'Rice', growth: 60, fill: '#7A8D5C' },
  { name: 'Corn', growth: 80, fill: '#B85C38' },
  { name: 'Potatoes', growth: 50, fill: '#A5BD79' },
];